import argparse
import json
import os
import torch.cuda


class ArgParser(object):
    def __init__(self):
        self.parser = argparse.ArgumentParser(description='Filter Discriminator')
        self.parser.add_argument('--batch_size', type=int, default=256,
                                 help='Batch size.')
        self.parser.add_argument('--model', type=str, required=True, choices=('', 'vgg19', 'alexnet', 'resnet50', 'fd'),
                                 help='If non-empty, train the specified model.')
        self.parser.add_argument('--ckpt_path', type=str, default='',
                                 help='Path from which to load checkpoint.')
        self.parser.add_argument('--dataset', type=str, choices=('cifar10', 'filters', 'random'), default='cifar10',
                                 help='Dataset to use.')
        self.parser.add_argument('--gpu_ids', type=str, default='3',
                                 help='Comma-separated list of IDs for GPUs to use.')
        self.parser.add_argument('--iters_per_print', type=int, default=512,
                                 help='Iterations between printing to the console.')
        self.parser.add_argument('--iters_per_visual', type=int, default=2048,
                                 help='Iterations between showing an example in TensorBoard.')
        self.parser.add_argument('--learning_rate', type=float, default=0.01,
                                 help='Initial learning rate.')
        self.parser.add_argument('--lr_decay_gamma', type=float, default=0.95,
                                 help='Multiply learning rate by this value every lr_decay_step epochs.')
        self.parser.add_argument('--lr_decay_step', type=int, default=1,
                                 help='Number of epochs between each multiply-by-gamma step.')
        self.parser.add_argument('--log_dir', type=str, default='logs',
                                 help='Directory for logs generated by TensorBoard.')
        self.parser.add_argument('--name', type=str, required=True, help='Name for experiment.')
        self.parser.add_argument('--num_workers', type=int, default=4,
                                 help='Number of worker thread per data loader.')
        self.parser.add_argument('--num_epochs', type=int, default=300,
                                 help='Number of epochs to train for. If 0, train forever.')
        self.parser.add_argument('--num_classes', type=int, default=10,
                                 help='Number of classes in labels for dataset.')
        self.parser.add_argument('--num_visuals', type=int, default=4, help='Maximum number of visuals per batch.')
        self.parser.add_argument('--max_ckpts', type=int, default=-1, help='Maximum number of checkpoints to keep.')
        self.parser.add_argument('--save_epochs', type=str, default='1,10,20,30',
                                 help='Comma-separated list of epochs after which to save a checkpoint.')
        self.parser.add_argument('--save_all', action='store_true',
                                 help='If set, save every epoch.')
        self.parser.add_argument('--save_dir', type=str, default='ckpts/',
                                 help='Directory for saving model checkpoints.')
        self.parser.add_argument('--sgd_momentum', type=float, default=0.9, help='Momentum for SGD.')
        self.parser.add_argument('--use_fd', action='store_true',
                                 help='If true, use filter discriminator during training.')
        self.parser.add_argument('--fd_lambda', type=float, default=10.,
                                 help='Weight for FD loss relative to regular loss with weight 1.')
        self.parser.add_argument('--fd_batch_size', type=int, default=64,
                                 help='Batch size for filter discriminator.')
        self.parser.add_argument('--fixed_lambda', action='store_true',
                                 help='If set, keep lambda fixed. Else use exponential decay.')
        self.parser.add_argument('--weight_decay', type=float, default=0.,
                                 help='Weight decay (i.e., L2 regularization factor).')

    def parse_args(self):
        args = self.parser.parse_args()

        # Set up additional arguments
        args.gpu_ids = [int(i) for i in str(args.gpu_ids).split(',') if int(i) >= 0]
        args.device = 'cuda' if len(args.gpu_ids) > 0 and torch.cuda.is_available() else 'cpu'
        if len(args.gpu_ids) > 0:
            torch.cuda.set_device(args.gpu_ids[0])
        args.save_epochs = [int(i) for i in str(args.save_epochs).split(',') if int(i) >= 0]

        if args.use_fd and not args.ckpt_path:
            raise ValueError('Must specify a checkpoint path for filter discriminator.')

        # Dump arguments to a JSON file
        args.save_dir = os.path.join(args.save_dir, args.name)
        os.makedirs(args.save_dir, exist_ok=True)
        with open(os.path.join(args.save_dir, 'args.json'), 'w') as fh:
            json.dump(vars(args), fh, indent=4, sort_keys=True)
            fh.write('\n')

        return args
